version: '3.8'
services:
  app:
    build: .
    container_name: Nubian-Fortune-Production
    ports:
      - '7000:7000'
    networks:
      - my-shared-network
    env_file:
      - ./server/.env
networks:
  my-shared-network:
    external: true